package org.apache.dubbo.Interface;

import java.lang;
import java.util;
import java.util.concurrent;
import org.apache.dubbo.rpc.model;
import org.apache.dubbo.common.config;
import java.util.function;

public interface DubboBootstrapInterface{
    DubboBootstrapInterface getInstance();
    DubboBootstrapInterface getInstance(ApplicationModel applicationModel);
    DubboBootstrapInterface newInstance();
    DubboBootstrapInterface newInstance(FrameworkModel frameworkModel);
    void reset();
    void reset(boolean destroy);
    void initialize();
    DubboBootstrapInterface start();
    DubboBootstrapInterface start(boolean wait);
    Future asyncStart();
    DubboBootstrapInterface stop();
    void destroy();
    boolean isInitialized();
    boolean isPending();
    boolean isRunning();
    boolean isStarting();
    boolean isStarted();
    boolean isStopping();
    boolean isStopped();
    DubboBootstrapInterface await();
    ReferenceCache getCache();
    ApplicationConfigInterface getApplication();
    void setTakeoverMode(BootstrapTakeoverModeInterface takeoverMode);
    BootstrapTakeoverModeInterface getTakeoverMode();
    ApplicationModel getApplicationModel();
    ConfigManagerInterface getConfigManager();
    DubboBootstrapInterface metadataReport(Consumer consumerBuilder);
    DubboBootstrapInterface metadataReport(String id, Consumer consumerBuilder);
    DubboBootstrapInterface metadataReport(MetadataReportConfigInterface metadataReportConfig);
    DubboBootstrapInterface metadataReports(List metadataReportConfigs);
    DubboBootstrapInterface application(String name);
    DubboBootstrapInterface application(String name, Consumer consumerBuilder);
    DubboBootstrapInterface application(ApplicationConfigInterface applicationConfig);
    DubboBootstrapInterface registry(Consumer consumerBuilder);
    DubboBootstrapInterface registry(String id, Consumer consumerBuilder);
    DubboBootstrapInterface registry(RegistryConfigInterface registryConfig);
    DubboBootstrapInterface registries(List registryConfigs);
    DubboBootstrapInterface protocol(Consumer consumerBuilder);
    DubboBootstrapInterface protocol(String id, Consumer consumerBuilder);
    DubboBootstrapInterface protocol(ProtocolConfigInterface protocolConfig);
    DubboBootstrapInterface protocols(List protocolConfigs);
    DubboBootstrapInterface service(Consumer consumerBuilder);
    DubboBootstrapInterface service(String id, Consumer consumerBuilder);
    DubboBootstrapInterface services(List serviceConfigs);
    DubboBootstrapInterface service(ServiceConfigInterface serviceConfig);
    DubboBootstrapInterface service(ServiceConfigInterface serviceConfig, ModuleModel moduleModel);
    DubboBootstrapInterface reference(Consumer consumerBuilder);
    DubboBootstrapInterface reference(String id, Consumer consumerBuilder);
    DubboBootstrapInterface references(List referenceConfigs);
    DubboBootstrapInterface reference(ReferenceConfigInterface referenceConfig);
    DubboBootstrapInterface reference(ReferenceConfigInterface referenceConfig, ModuleModel moduleModel);
    DubboBootstrapInterface provider(Consumer builderConsumer);
    DubboBootstrapInterface provider(String id, Consumer builderConsumer);
    DubboBootstrapInterface provider(ProviderConfigInterface providerConfig);
    DubboBootstrapInterface providers(List providerConfigs);
    DubboBootstrapInterface provider(ProviderConfigInterface providerConfig, ModuleModel moduleModel);
    DubboBootstrapInterface consumer(Consumer builderConsumer);
    DubboBootstrapInterface consumer(String id, Consumer builderConsumer);
    DubboBootstrapInterface consumer(ConsumerConfigInterface consumerConfig);
    DubboBootstrapInterface consumers(List consumerConfigs);
    DubboBootstrapInterface consumer(ConsumerConfigInterface consumerConfig, ModuleModel moduleModel);
    DubboBootstrapInterface module(ModuleConfigInterface moduleConfig);
    DubboBootstrapInterface module(ModuleConfigInterface moduleConfig, ModuleModel moduleModel);
    DubboBootstrapInterface configCenter(Consumer consumerBuilder);
    DubboBootstrapInterface configCenter(String id, Consumer consumerBuilder);
    DubboBootstrapInterface configCenter(ConfigCenterConfigInterface configCenterConfig);
    DubboBootstrapInterface configCenters(List configCenterConfigs);
    DubboBootstrapInterface monitor(MonitorConfigInterface monitor);
    DubboBootstrapInterface metrics(MetricsConfigInterface metrics);
    DubboBootstrapInterface ssl(SslConfigInterface sslConfig);
    ModuleInterface newModule();
    ModuleInterface newModule(ModuleConfigInterface moduleConfig);
    DubboBootstrapInterface endModule();

}